# vim:set expandtab shiftwidth=4 filetype=yaml foldlevel=3:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/shared-config.git
# ::: :/.github/workflows/lint.yaml
#
#

name: Lint

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch: {}

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        uses: chewygumxx/.github/.github/workflows/lint.yaml@v1
